name: Check links

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install markdown-link-check
        run: npm install -g markdown-link-check

      - name: Check links
        run: markdown-link-check ./README.md
